export const LOGIN_TODO_REQUEST = "LOGIN_TODO_REQUEST";
export const LOGIN_TODO_SUCCESS = "LOGIN_TODO_SUCCESS";
export const LOGIN_TODO_FAILURE = "LOGIN_TODO_FAILURE";

export const LOGOUT_TODO_REQUEST = "LOGOUT_TODO_REQUEST";
export const LOGOUT_TODO_SUCCESS = "LOGOUT_TODO_SUCCESS";
export const LOGOUT_TODO_FAILURE = "LOGOUT_TODO_FAILURE";
