export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const POST_TASKS_REQUEST = "POST_TASKS_REQUEST";
export const POST_TASKS_SUCCESS = "POST_TASKS_SUCCESS";
export const POST_TASKS_FAILURE = "POST_TASKS_FAILURE";
